
jobs:
  include:
    - stage: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh
